const businessData = [
  { "name": "Nsa Travels", "url": "https://nsatravels.lk/", "sector": "Travel / Agencies" },
  { "name": "Ceylonlandd", "url": "https://ceylonlandd.lk/", "sector": "Salon" },
  { "name": "Drbrothers", "url": "https://drbrothers.lk/", "sector": "Vehicles" },
  { "name": "Nelumkole", "url": "https://nelumkole.lk/", "sector": "Hotel" },
  { "name": "Ktlholdings", "url": "https://ktlholdings.lk/", "sector": "Logistics" },
  { "name": "Goodwins", "url": "https://goodwins.lk/", "sector": "Home Decoration" },
  { "name": "Skyupholstery", "url": "https://skyupholstery.lk/", "sector": "Home Decoration" },
  { "name": "Palliyagurutech", "url": "https://palliyagurutech.lk/", "sector": "CCTV" },
  { "name": "Sulikosuper", "url": "https://sulikosuper.lk/", "sector": "Food City" },
  { "name": "Nadisports", "url": "https://nadisports.lk/", "sector": "Sport" },
  { "name": "Gurugetextiles", "url": "https://gurugetextiles.lk/", "sector": "Textiles" },
  { "name": "Babysark", "url": "https://babysark.lk", "sector": "Baby" },
  { "name": "Senumediaproductions", "url": "https://senumediaproductions.lk/", "sector": "Media Solutions" },
  { "name": "Arathanamedicalcentre", "url": "https://arathanamedicalcentre.lk/", "sector": "Medical" },
  { "name": "Leavesofgreen", "url": "https://leavesofgreen.lk/", "sector": "Land Development" },
  { "name": "Susaru", "url": "https://susaru.lk/", "sector": "Export" },
  { "name": "Saharaagencies", "url": "https://saharaagencies.lk/", "sector": "Travel / Agencies" },
  { "name": "Threebrotherssalon", "url": "http://threebrotherssalon.lk", "sector": "Salon" },
  { "name": "Hyperperformance", "url": "https://hyperperformance.lk/", "sector": "Vehicles" },
  { "name": "Realmatharabathkade", "url": "https://realmatharabathkade.lk/", "sector": "Hotel" },
  { "name": "Pacificenterprises", "url": "https://pacificenterprises.lk/", "sector": "Logistics" },
  { "name": "Ayanatilemarketing", "url": "https://ayanatilemarketing.lk/", "sector": "Home Decoration" },
  { "name": "Thesupplementhouse", "url": "https://thesupplementhouse.lk/", "sector": "Sport" },
  { "name": "Kaduwelaadumkade", "url": "https://kaduwelaadumkade.lk/", "sector": "Textiles" },
  { "name": "Betatravels", "url": "https://betatravels.lk/", "sector": "Travel / Agencies" },
  { "name": "Rosepetals", "url": "https://rosepetals.lk/", "sector": "Salon" },
  { "name": "Serendibtyre", "url": "https://serendibtyre.lk/", "sector": "Vehicles" },
  { "name": "Greentophotel", "url": "https://greentophotel.lk/", "sector": "Hotel" },
  { "name": "Mahadivulwewaenterprises", "url": "https://mahadivulwewaenterprises.lk/", "sector": "Logistics" },
  { "name": "Dineshfurniture", "url": "https://dineshfurniture.lk/", "sector": "Home Decoration" },
  { "name": "Sportzone", "url": "https://sportzone.lk/", "sector": "Sport" },
  { "name": "Srforeignemploymentagency", "url": "https://srforeignemploymentagency.lk/", "sector": "Travel / Agencies" },
  { "name": "Unsautomobile", "url": "https://unsautomobile.lk/", "sector": "Vehicles" },
  { "name": "Viprest", "url": "https://viprest.lk/", "sector": "Hotel" },
  { "name": "Bigwinelectronics", "url": "https://bigwinelectronics.lk/", "sector": "Home Decoration" },
  { "name": "Eurozoneforeignemployment", "url": "https://eurozoneforeignemployment.lk/", "sector": "Travel / Agencies" },
  { "name": "Wayambacars", "url": "https://wayambacars.lk/", "sector": "Vehicles" },
  { "name": "Newbarathmetal", "url": "https://newbarathmetal.lk/", "sector": "Home Decoration" },
  { "name": "Pamodadistributor", "url": "https://pamodadistributor.lk/", "sector": "Vehicles" },
  { "name": "Royalinterior", "url": "https://royalinterior.lk/", "sector": "Home Decoration" },
  { "name": "Royalleather", "url": "https://royalleather.lk/", "sector": "Home Decoration" },
  { "name": "Amilaelectronics", "url": "https://amilaelectronics.lk/", "sector": "Home Decoration" },
];

// Export for use in modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = businessData;
}
