const businessData = [
  { "name": "Thalpe Serenity Shore", "url": "https://thalpeserenityshore.lk/", "sector": "Hotel & Res" },
  { "name": "Lanka Lighting", "url": "https://lankalighting.lk/", "sector": "Light Shop" },
  { "name": "Multy Fabric", "url": "https://multifabric.lk/", "sector": "Cloth Store" },
  { "name": "SKY ONE", "url": "https://skyonetravels.lk/", "sector": "Travel" },
  { "name": "Celo City", "url": "https://celocity.lk/", "sector": "Mobile Shop" },
  { "name": "Marutham food products Pvt Ltd", "url": "https://marutham.lk/", "sector": "Food and Agreclutre" },
  { "name": "Al-Latifa Travels and Tours", "url": "https://allatifatravels.lk/", "sector": "Travel" },
  { "name": "Manal Men's", "url": "https://manalmens.lk/", "sector": "Cloth Store" },
  { "name": "I Lanka Mobile", "url": "https://ilankamobile.lk/", "sector": "Mobile Shop" },
  { "name": "White Palace Banquet Hall (PVT) LTD", "url": "https://whitepalace.lk/", "sector": "Wedding" },
  { "name": "gprsolar", "url": "https://gprsolar.lk/", "sector": "Energy" },
  { "name": "Asian Hotel", "url": "https://asianhotel.lk/", "sector": "Res" },
  { "name": "MRGOLD PVT LTD", "url": "https://mrgold.lk/", "sector": "RentCar" },
  { "name": "ULTRA RAPID LAUNDROMAT", "url": "https://ultrarapidlaundromat.lk/", "sector": "LAUNDROMAT" },
  { "name": "manojgroup", "url": "https://manojgroup.lk/", "sector": "Toy Shop" },
  { "name": "Jeyam Tattoo Art (Pvt)ltd", "url": "https://jeyamtattooart.lk/", "sector": "Tatoo" },
  { "name": "RosySaloon", "url": "https://Rosysalon.lk/", "sector": "Saloon" },
  { "name": "Saloon Me", "url": "https://salonmebeautycare.lk/", "sector": "Saloon" },
  { "name": "KITCHEN WORLD", "url": "https://kitchenworld.lk/", "sector": "KitchenShop" },
  { "name": "Kayal beauty lounge", "url": "https://kayalbeautylounge.lk/", "sector": "Beauti Shop" },
  { "name": "Vintage Restaurent And Café (50K)", "url": "https://vintagerestaurent.lk/", "sector": "restaurent Shop" },
  { "name": "kfashion", "url": "https://kfashion.lk/", "sector": "Fashion Shop" },
  { "name": "Zim & D Ceylon Agro Pvt Ltd", "url": "https://Zimandd.lk/", "sector": "Food and Agreclutre" },
  { "name": "Kandy Lanka Foreign Employment Agency", "url": "https://kandylanka.lk/", "sector": "Foreign Employment Agency" },
  { "name": "Trendz mania", "url": "https://glowupcosmetics.lk/", "sector": "Perfume Shop" },
  { "name": "Vivaha saree mandir", "url": "https://vivahasareemandir.lk/", "sector": "Saree Shop" },
  { "name": "Dilshan Aluminium PVT LTD (50K)", "url": "https://dilshanaluminium.lk/", "sector": "Light Shop" },
  { "name": "AVS Decoration", "url": "https://avsdecoration.lk/", "sector": "Decoration" },
  { "name": "Toy Garage (pvt) Ltd", "url": "https://ToyGarage.lk/", "sector": "Toy Shop" },
  { "name": "Krishmart International (pvt) Ltd", "url": "https://Krishmart.lk/", "sector": "Food Import & Export" },
  { "name": "Royal Rent", "url": "https://royalrentacar.lk/", "sector": "Rent Car" },
  { "name": "Alumin Engineering pvt ltd", "url": "https://aluminengineering.lk/", "sector": "aluminengineering" },
  { "name": "The Display Kade", "url": "https://thedisplaykade.lk/", "sector": "Phone Displays" },
  { "name": "lorries for hire", "url": "https://lorriesforhire.lk/", "sector": "rent lorries" },
  { "name": "Venus 91 nail salon", "url": "https://venus91.lk/", "sector": "nail salon" },
  { "name": "GK Star (Pvt) Ltd", "url": "https://gkstar.lk/", "sector": "Textile" },
  { "name": "Marutham food products Pvt Ltd", "url": "https://marutham.lk/", "sector": "food manufactring" },
  { "name": "PROMAX REALTY GLOBAL", "url": "https://promaxrealtyglobal.lk/", "sector": "Constreuction Company" },
  { "name": "Gnanapalamotors", "url": "https://gnanapalamotors.lk/", "sector": "Car Service Company" },
  { "name": "Thinethara Lands", "url": "https://thinethralands.lk/", "sector": "land company" }
];

// Export for use in modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = businessData;
}
